### ISSUE TITLE
MRO - On the update pop up message, lines to enter update notes ?

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#131]
Can we use the white space below to enter up to 5 lines of more explanation on the fixes ?
Example:
- Added part barcode feature
- Changes to the safety certificate
- Improved performance
- Misc bug fixes.

Would be nice to tell the users what main updates are going in. I would be providing you with the release notes every time there was a release.

Let me know...

![image](https://cloud.githubusercontent.com/assets/5666297/10203595/f3b860f2-6784-11e5-82b7-0155e84571e1.png)

**Comment by d3ssupport** [comment]
ACKNOWLEDGE 



Sent from my Samsung Galaxy smartphone.

Can we use the white space below to enter up to 5 lines of more explanation on the fixes ? Example: Added part barcode feature Changes to the safety certificate Improved performance Misc bug fixes. Would be nice to tell the users what main updates are going in. I would be providing you with the release notes every time there was a release. Let me know... —Reply to this email directly or view it on GitHub.

**Comment by giovanicani** [comment]
completed, and tested
