### ISSUE TITLE
MRO - Parts barcoding

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#132]
Which field is the parts barcoding is matching against ? I believe it is the part number, please make it to cross reference the barcode_number field in the inv_parts_wv view.

![image](https://cloud.githubusercontent.com/assets/5666297/10203707/97c986ee-6785-11e5-8130-fcdc0ed8c0ed.png)

**Comment by d3ssupport** [comment]
Ok.. we will work on it. 



Sent from my Samsung Galaxy smartphone.

Which field is the parts barcoding is matching against ? I believe it is the part number, please make it to cross reference the barcode_number field in the inv_parts_wv view. —Reply to this email directly or view it on GitHub.

**Comment by giovanicani** [comment]
Looks like the barcode column is incorrectly showing the same value as the part#. Please show the field inv_parts.barcode_number

![image](https://cloud.githubusercontent.com/assets/5666297/10281768/c710776a-6b44-11e5-832d-3febc5a74550.png)

**Comment by giovanicani** [comment]
Please change the word "CODE" to PART#
![image](https://cloud.githubusercontent.com/assets/5666297/10281825/1d298420-6b45-11e5-9118-156e749244ec.png)

**Comment by d3sqa** [comment]
Done. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Please change the word: Cancel to Close.
Add camera feature to read barcode
When pressing OK, add part to RO and clean field to read another barcode. ** Do not close popup window. Popup window will only be closed when the close button is pressed.


![image](https://cloud.githubusercontent.com/assets/5666297/10431593/f0620dba-70d3-11e5-917a-cbdc94cf0d90.png)

**Comment by d3ssupport** [comment]
Acknowledge 



Sent from my Samsung Galaxy smartphone.

Please change the word: Cancel to Close. Add camera feature to read barcode When pressing OK, add part to RO and clean field to read another barcode. ** Do not close popup window. Popup window will only be closed when the close button is pressed. —Reply to this email directly or view it on GitHub.

**Comment by d3sqa** [comment]
Scanning barcode via camera and pop-up window related functionality done. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works great. thanks!
