### ISSUE TITLE
MRO - Break Inspection Form (Government Requirement)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#134]
As discussed please work this activity.

[BRAKEINSPECTIONREPORT (1).pdf](https://github.com/GCSO2/D3SRel2.0/files/5490/BRAKEINSPECTIONREPORT.1.pdf)

**Comment by giovanicani** [comment]
Team is currently working on this activity.

**Comment by d3ssupport** [comment]
We are working on it. 

Thanks



Sent from my Samsung Galaxy smartphone.

As discussed please work this activity. BRAKEINSPECTIONREPORT (1).pdf —Reply to this email directly or view it on GitHub.

**Comment by giovanicani** [comment]
Good Job, a few feedbacks:

1. Please make the NEW a check box instead of a radio button
2. Remove "or" after NEW. User need to enter reading when NEW is checked
3. Scroll bar on the right is going over some of the fields, please make the bar thinner.
4. Shift a bit down the REAR arrow. No need to make it dynamic.

![image](https://cloud.githubusercontent.com/assets/5666297/10281576/6b168a04-6b43-11e5-9ffa-c1491c04b21e.png)

**Comment by giovanicani** [comment]
Progress has been made.

Please check the following items:

- Tab label needs to be changed to Brake Inspection;
- Reading field needs to be enabled even if NEW is not checked;
- Reading should be able to accept alpha numeric like: 1/5;
- Keyboard navigation (tab and shift tab);
- Tweaks on the report like:
-- MTO Inspection starting on a new page;
-- Try to keep the check list in one page;

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Hi Please make the following adjustments:

1. Instead of PM-S, make the brake inspection required every time there is a check list (it will be in PM-A, PM-S, PM-001);

2. Allow user to close window using the close at the top right corner, however RO cannot be COMPLETED if check list is not completely done. RO can be placed on HOLD, but not completed if the CL is not fully done.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
For checklist A, 001 and S, brake inspection tab is now available. Checklist validation on hold and complete has been implemented from mobile side. Ready to test in UAT Environment.

Please note that when the intermediate (incomplete) checklist data is entered and RO being put onhold, the data is not reflecting at cloud. However upon completion, the data does reflect. We are working on it.

**Comment by giovanicani** [comment]
Currently testing with our service manager

**Comment by giovanicani** [comment]
Tested all is working, except the following:

1. If at least one axle is not N/A... signature of the Brake Form should be mandatory
2. Add 7 axle on the drop list.

**Comment by d3sqa** [comment]
Signature has been made mandatory. Ready to test in UAT Environment

Work in progress on adding 7 into the Axle drop down

**Comment by giovanicani** [comment]
I see the 7 axle there... are you still working on this ? thanks.

**Comment by d3ssupport** [comment]
Hi. Yes we are still working on this. Thanks


-------- Original message --------

**Comment by d3sqa** [comment]
7th axle has been added from mobile. Data is also retrieved successfully when RO is resumed.

However, there is some issue at cloud with the Brake Percentages being replicated from 6th to 7th axle. We are working on it, will let you know after it gets done.

**Comment by d3sqa** [comment]
7 axle has been added and is functional on both mobile and cloud. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Pending Gio's testing

**Comment by giovanicani** [comment]
This has been released. Good Job!
