### ISSUE TITLE
MRO - Expland by default Equipment Information instead of labour and parts

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#135]
When opening the MRO Details screen, please have the Equipment Information section expanded instead of Labour and Parts.

**Comment by d3ssupport** [comment]
OK we will take care of it. 


Thanks



Sent from my Samsung Galaxy smartphone.

When opening the MRO Details screen, please have the Equipment Information section expanded instead of Labour and Parts. —Reply to this email directly or view it on GitHub.

**Comment by d3sqa** [comment]
Ready to test in UAT Environment

**Comment by giovanicani** [comment]
done and promoted to prod. thanks!
