### ISSUE TITLE
MRO - Add ... button for Customer as well

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#136]
Similarly to the location, add the ... button for customer, so that user can select last 5 customers from a popup box.

**Comment by d3ssupport** [comment]
OK WE WILL WORK ON IT.

THANKS


Sent from my Samsung Galaxy smartphone.

Similarly to the location, add the ... button for customer, so that user can select last 5 customers from a popup box. —Reply to this email directly or view it on GitHub.

**Comment by giovanicani** [comment]
done.test OK!
