### ISSUE TITLE
RO Date validation

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#137]
As discussed please do not allow them to select future dates on the RO date and on the certificate date. Also for the RO DATE they should only be able to backdate up to 5 days.

**Comment by d3ssupport** [comment]
Acknowledge.


Sent from my Samsung device


-------- Original message --------

**Comment by giovanicani** [comment]
Giovani to check with users how to handle backdating RO logic for ROs which are on HOLD.

**Comment by giovanicani** [comment]
Giovani still need to talk to the users on the hold situation.

**Comment by giovanicani** [comment]
Hi Please change validation to not allow back date more than 30 days, instead of 5. Thanks!

**Comment by d3ssupport** [comment]
We will change into 30 Days.. 



Sent from my Samsung Galaxy smartphone.

Hi Please change validation to not allow back date more than 30 days, instead of 5. Thanks! —Reply to this email directly or view it on GitHub.

**Comment by d3sqa** [comment]
RO Date validation has been changed from 5 days to 30 days backdated. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works. thanks
