### ISSUE TITLE
MRO - Not in EMDECS - Again! Please fix root cause

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#139]
Another issue where the MRO is not sent into EMDECS and no information on the log.

** I need the root cause be identified and fixed **

![image](https://cloud.githubusercontent.com/assets/5666297/10310352/8de855fe-6c0f-11e5-9567-229ae7070ee2.png)

**Comment by d3ssupport** [comment]
Acknowledge.. we are working on it. 
Thanks
D3S Team



Sent from my Samsung Galaxy smartphone.

Another issue where the MRO is not sent into EMDECS and no information on the log. ** I need the root cause be identified and fixed ** —Reply to this email directly or view it on GitHub.

**Comment by giovanicani** [comment]
working on it. Removing the restriction from client side. EMDECS needs to be engaged from the server side only.

**Comment by giovanicani** [comment]
Another one.

![image](https://cloud.githubusercontent.com/assets/5666297/10344356/bc78d740-6cf0-11e5-98f5-bf16640b86ae.png)

**Comment by tufailzafar** [comment]
We are working on it..

**Comment by d3sqa** [comment]
Done. Please verify

**Comment by giovanicani** [comment]
What was done ?

--
Giovani Cani

**Comment by d3ssupport** [comment]
Service 2 direct called from API without involving client in the process. 
As discussed that Removing the restriction from client side. EMDECS needs to be engaged from the server side only.

**Comment by giovanicani** [comment]
Ok. Will test

--
Giovani Cani

**Comment by giovanicani** [comment]
There is not much what I can test for this one... will close since the issue hasn't occurred while testing the other issues.
