### ISSUE TITLE
MRO - M41 getting old RO popup, but he doesn't have old ROs

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#140]
Why ? see below:

![screen shot 2015-10-06 at 10 08 03 am](https://cloud.githubusercontent.com/assets/5666297/10310891/44731e6a-6c12-11e5-8726-c87e76b3075c.png)

![screen shot 2015-10-06 at 10 08 18 am](https://cloud.githubusercontent.com/assets/5666297/10310892/45e6d548-6c12-11e5-9a75-a4446bc9d3b3.png)

**Comment by d3ssupport** [comment]
Acknowledge. 
We are working on it. 

Thanks
D3S Team



Sent from my Samsung Galaxy smartphone.

Why ? see below: —Reply to this email directly or view it on GitHub.

**Comment by giovanicani** [comment]
Date format issue, ready to be tested.

**Comment by giovanicani** [comment]
works. Thanks!
