### ISSUE TITLE
Remind user to take pictures when labour reason = DAMAGE

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#141]
Add a new flag on the reasons tablet / view called:

image_recommended_flag VARCHAR2(1) Y/N DEFAULT N

For 2 - Damage, make it Y.

As the last validation for the labour line, when  reason has image_recommended_flag equal to Y and there is no picture for that labour and the user presses OK, prompt the following message:

"It is recommended to take pictures for this labour line."

Have 2 buttons: "Take Picture", "Close"

If take a picture is selected then go into the picture taking screen.
If close is selected close the window.

![image](https://cloud.githubusercontent.com/assets/5666297/10374466/58a07ada-6dc1-11e5-894f-dfece88313a5.png)

**Comment by d3ssupport** [comment]
Acknowledge. Thanks


Sent from my Samsung device


-------- Original message --------

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Works well... please just place Take Picture button on the left and Close on the right.

![image](https://cloud.githubusercontent.com/assets/5666297/10431409/d98a6520-70d2-11e5-8f32-4373c53f27dc.png)

**Comment by d3ssupport** [comment]
Ok.. we will change the place. 

Thanks



Sent from my Samsung Galaxy smartphone.

Works well... please just place Take Picture button on the left and Close on the right. —Reply to this email directly or view it on GitHub.

**Comment by d3sqa** [comment]
Button placement swapped. Ready for test in UAT Environment

**Comment by giovanicani** [comment]
works. thanks!
