### ISSUE TITLE
MRO Inquiry

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#142]
Add total labour hours on the inquiry completed tab. This will help mechanic reconcile against they pay check. Can be placed after RO#. Column title can be called "Hours".

Shorten size for Lic. Plate (change to Plate), PO# and RO#. 

![image](https://cloud.githubusercontent.com/assets/5666297/10431771/f43d42a0-70d4-11e5-8509-e8296171a18f.png)

**Comment by d3ssupport** [comment]
Acknowledge 

Thanks
Anwar



Sent from my Samsung Galaxy smartphone.

Add total labour hours on the inquiry completed tab. This will help mechanic reconcile against they pay check. Can be placed after RO#. Column title can be called "Hours". Shorten size for Lic. Plate (change to Plate), PO# and RO#. —Reply to this email directly or view it on GitHub.

**Comment by d3sqa** [comment]
Hours column has been added to the Completed folded view. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Please align numbers to the right. thanks

**Comment by d3ssupport** [comment]
Acknowledge 

Thanks
D3S Team



Sent from my Samsung Galaxy smartphone.

Please align numbers to the right. thanks —Reply to this email directly or view it on GitHub.

**Comment by d3sqa** [comment]
Number field has been aligned to the right side. Ready to test in UAT Environment.

**Comment by giovanicani** [comment]
works. thanks!
