### ISSUE TITLE
Cloud - Add Filter ** Please be mindful of performance degradation **

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#143]
Please add the following filters on CLOUD:

RO #: Needs to use an index and only matches exact number.
RO Date (from / to)
Mechanic (use assigned to)
PO#
Trailer Number
Unit Number
Exclude Void (check box default checked)
Status: On Hold (check box) Work In Progress (check box) All (check box - checked by default)

![image](https://cloud.githubusercontent.com/assets/5666297/10431858/93831452-70d5-11e5-81f6-2164d70999f4.png)

**Comment by d3ssupport** [comment]
Acknowledge 

Thanks
D3S Team



Sent from my Samsung Galaxy smartphone.

Please add the following filters on CLOUD: RO #: Needs to use an index and only matches exact number. RO Date (from / to) Mechanic (use assigned to) PO# Trailer Number Unit Number Exclude Void (check box default checked) —Reply to this email directly or view it on GitHub.

**Comment by d3sqa** [comment]
Check boxes for 'Work in progress', 'On hold', 'All' and 'Exclude Void' have been added and made functional. Ready to test in UAT Environment

Work in progress on 'Filter' feature.

**Comment by d3sqa** [comment]
Filter has been implemented completely. Ready to test UAT Environment

**Comment by giovanicani** [comment]
Works well, however please do the following tweaks:

1. At the top, change the word "Search" to "Quick Search (RO#)"
2. At the Apply Filter box... please change Cancel to Close
3. When pressing search, can you please leave the box visible so that user can do further changes on the filter. Only pressing Close would actually close the search box.

![image](https://cloud.githubusercontent.com/assets/5666297/10586107/a46d5b04-7668-11e5-87ff-054d438c32c3.png)

**Comment by d3ssupport** [comment]
Acknowledge 

Thanks
D3S Team

Works well, however please do the following tweaks: At the top, change the word "Search" to "Quick Search (RO#)" At the Apply Filter box... please change Cancel to Close When pressing search, can you please leave the box visible so that user can do further changes on the filter. Only pressing Close would actually close the search box. —Reply to this email directly or view it on GitHub.

**Comment by d3ssupport** [comment]
Acknowledge


-------- Original message --------

**Comment by d3sqa** [comment]
The above mentioned tweaks have been done. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
done.
