### ISSUE TITLE
MRO - Make Labour notes same font and multi-line

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#144]
Please see image below, please make the labour notes: (a) multi-line, (b) use the same font (smaller) that is used in the rest of the screen.

![image](https://cloud.githubusercontent.com/assets/5666297/10457556/ee105eec-7194-11e5-934e-d2eccea601c4.png)

**Comment by d3ssupport** [comment]
Acknowledge. 

Thanks
D3S Team


Sent from my Samsung Galaxy smartphone.

Please see image below, please make the labour notes: (a) multi-line, (b) use the same font (smaller) that is used in the rest of the screen. —Reply to this email directly or view it on GitHub.

**Comment by giovanicani** [comment]
works. thanks.
