### ISSUE TITLE
MRO - Parts Barcode tweaking (in order to speed process)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#145]
Please make the OK button default. I.e.: If ENTER is pressed on the field, functionality on the OK button will be triggered.

On the barcode field, if system detects asterisk (*) at the beginning and asterisk at the end, then auto perform OK functionality. Example: **P010101*, kindly note that you will need to remove the 2 asterisk when searching for the parts barcode on the database.

![image](https://cloud.githubusercontent.com/assets/5666297/10458088/175fd4a6-7197-11e5-8bb0-3977471ae56b.png)

**Comment by d3ssupport** [comment]
Acknowledge. 

Thanks
D3S Team. 


Sent from my Samsung Galaxy smartphone.

Please make the OK button default. I.e.: If ENTER is pressed on the field, functionality on the OK button will be triggered. On the barcode field, if system detects asterisk () at the beginning and asterisk at the end, then auto perform OK functionality. Example: *P010101*, kindly note that you will need to remove the 2 asterisk when searching for the parts barcode on the database. —Reply to this email directly or view it on GitHub.

**Comment by d3sqa** [comment]
Part addition upon pressing Enter key and auto addition via asterisks  has been done. Ready to test in UAT Environment.

**Comment by giovanicani** [comment]
works. thanks!
