### ISSUE TITLE
MRO - Be able to write on the picture

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#146]
Can you see if it is possible to add the ability to write the picture after was taken and before was saved ?
User should be able to undo all edits.

Scribbling on the picture should only be allowed when the picture is taken from the labour section.

![image](https://cloud.githubusercontent.com/assets/5666297/10515084/bac0f8d0-731f-11e5-8f06-f94109177760.png)

**Comment by d3ssupport** [comment]
Acknowledge 

Thanks
D3S Team


Can you see if it is possible to add the ability to write the picture after was taken and before was saved ? User should be able to undo all edits. —Reply to this email directly or view it on GitHub.

**Comment by giovanicani** [comment]
work in progress. Some improvements required, but functionality is there.

**Comment by d3sqa** [comment]
Writing on picture's feature has been implemented completely. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works great. thanks
