### ISSUE TITLE
MRO - Please make * as delimiter for all barcode fields - AUTO OK

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#147]
Like it was done on the parts... on the Trailer barcode fields (all barcode fields in the MRO), if the system detects * at the beginning and * at the end, please AUTO OK / NEXT. Remove the * to do the search on the database

Example: 
![image](https://cloud.githubusercontent.com/assets/5666297/10515994/1bcb32fe-7324-11e5-9d62-732bdc07be02.png)

Also make all barcode fields auto selectable when the focus is on the field. (like it was done on other fields of the program, ie: customer, location, etc...)

**Comment by d3ssupport** [comment]
Acknowledge. 

Thanks
D3S Team

Like it was done on the parts... on the Trailer barcode fields (all barcode fields in the MRO), if the system detects * at the beginning and * at the end, please AUTO OK / NEXT. Remove the * to do the search on the database Example: Also make all barcode fields auto selectable when the focus is on the field. (like it was done on other fields of the program, ie: customer, location, etc...) —Reply to this email directly or view it on GitHub.

**Comment by d3sqa** [comment]
AUTO OK feature has been implemented on the barcode fields.
Barcode auto selection feature is also done. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works. thanks.
