### ISSUE TITLE
Bug - Why ERROR MROs are not showing in the top of the grid ?

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#149]
Why ERROR MROs are not showing in the top of the grid ? Please correct this ASAP. thanks!

![image](https://cloud.githubusercontent.com/assets/5666297/10801257/eba7e1e4-7d8c-11e5-807d-4c85a954734a.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done.
ROs in ERROR are now displayed on top of the grid

**Comment by giovanicani** [comment]
verified.
