### ISSUE TITLE
Several ROs are going into ACTION REQUIRED

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#150]
There are several ROs not getting into EMDECS and this will be affecting payroll again. PLEASE make sure you go through all ROs in ACTION REQUIRED and fixed them.

Looks like Shawn needs permission, please give permission to Shawn. And re-submit RO.
The other ones D3S is re-submitting the same request twice or issues on the XML.

![image](https://cloud.githubusercontent.com/assets/5666297/10804362/7a50c450-7d9d-11e5-9973-54b1cb6d0353.png)

![image](https://cloud.githubusercontent.com/assets/5666297/10804396/b0392576-7d9d-11e5-8407-54f69f93b4ee.png)

![image](https://cloud.githubusercontent.com/assets/5666297/10804446/db3badca-7d9d-11e5-9822-7a0533d20cad.png)

etc...

**Comment by d3sqa** [comment]
We are looking into it

**Comment by gchan-trailcon** [comment]
Hi D3S team, would you please provide an update?  Thanks

**Comment by d3ssupport** [comment]
Hi Gary,

We are analysing the ROs which were not successfully committed to EMDECS

Uptil now, we have found the reason for the following ROs as to why are they in error:

R005729
R005724
R005738
R005714
R005711

The mechanic for above ROs is Shawn Ferguson and for this user the 'mobuse_id' does not exists in EMDECS. Kindly add the id against this user.

For ROs:

R005379
R005681

The EMDECS parser does not accept Unicode characters. Please find attached screen shots. 

For other ROs, analysis is in progress.  We will let you know about our findings in a while.

Thanks

Sent from Samsung Mobile

-------- Original message --------
From: gchan-trailcon 
Date:29/10/2015 18:40 (GMT+05:00) 
To: "GCSO2/D3SRel2.0" 
Subject: Re: [D3SRel2.0] Several ROs are going into ACTION REQUIRED (#150) 

Hi D3S team, would you please provide an update? Thanks

**Comment by gchan-trailcon** [comment]
Hi,

Shawn should be using W99 or W98.  Are you able to find out what user he logged in as?

W99 and W98 are already set up in EMDECS.  And Shawn has been using them since the old MRO.

**Comment by d3ssupport** [comment]
Hi gary. User logged was sf001 and mobuse id is not defined against this user. Thanks


-------- Original message --------

**Comment by gchan-trailcon** [comment]
I am asking Giovani what username should Shawn use.
D3S, are you able to change the user of these RO to W99?

**Comment by gchan-trailcon** [comment]
Hi D3S,

For ROs: R005379 R005681
I don't see the attached screen shots.  Would you please send again?

**Comment by d3ssupport** [comment]
Yeah sure

Please find attached image files namely p1 and p2.

Thanks


Sent from Samsung Mobile

-------- Original message --------

**Comment by gchan-trailcon** [comment]
Sorry, I don't see them in Github, nor in the email at all.

**Comment by d3ssupport** [comment]
Gary we have change user sf001 to w99 againt these two RO. Thanks


-------- Original message --------

**Comment by gchan-trailcon** [comment]
Okay, I can see the screenshots in the email now.
I am not sure how the user enter those characters.  But can the system disallow these characters to be entered? Or convert them to non-unicode characters?

And in the Dashboard, they are displayed normally, except the "&LRM;" character string on each:

"REPLACE EMERGENCY GLADHAND, RETAINING BOLT SNAPPED OFF APPEARS TO HAVE BEEN CUT BY GRINDER. I SUSPECT THE COLDLOGIC WAREHOUSE COULDN'T GET A GLADHAND LOCK OFF AND HAD TO CUT IT OFF DAMAGING THE GLADHAND. &LRM;"

"L/S AND CENTRE PLATES PULLED UP AND PIECES BROKEN OFF&LRM;. CUT OUT, PLATED AND WELDED 3X25" SECTION OF  FLOOR (USED PART)."

**Comment by gchan-trailcon** [comment]
No, only change to W99 for these RO:
R005729 R005724 R005738 R005714 R005711

**Comment by d3ssupport** [comment]
Yes gary we have only change against those Ro you have mentioned. Today same user also create RO and we also changed these user id too. Thanks

-------- Original message --------

**Comment by d3ssupport** [comment]
Garry.. 
We have update uni.code.now you can approve.  we can not convert it because EMDECS is not accepting such uni.codes. 

Thanks
D3S Team

Okay, I can see the screenshots in the email now. I am not sure how the user enter those characters. But can the system disallow these characters to be entered? Or convert them to non-unicode characters? And in the Dashboard, they are displayed normally, except the "&LRM;" character string on each: "REPLACE EMERGENCY GLADHAND, RETAINING BOLT SNAPPED OFF APPEARS TO HAVE BEEN CUT BY GRINDER. I SUSPECT THE COLDLOGIC WAREHOUSE COULDN'T GET A GLADHAND LOCK OFF AND HAD TO CUT IT OFF DAMAGING THE GLADHAND. &LRM;" "L/S AND CENTRE PLATES PULLED UP AND PIECES BROKEN OFF&LRM;. CUT OUT, PLATED AND WELDED 3X25" SECTION OF FLOOR (USED PART)." —Reply to this email directly or view it on GitHub.

**Comment by gchan-trailcon** [comment]
Okay, Now is correct.  You scared me when you said "we have change user sf001 to w99 againt these TWO RO" as the 2 RO are for M60 not W99.

**Comment by gchan-trailcon** [comment]
Are we able to prevent unicode from typing in?  Or automatically removing them before import to EMDECS?

**Comment by d3ssupport** [comment]
We will work on it. Thanks


-------- Original message --------

**Comment by giovanicani** [comment]
How come the user is entering unicode chars? This was never an issue on the previous MRO app. This must be fixed in the mobile app.

Also we need to know why D3S is sending twice the same RO into EMDECS. There are 4 MROs stucked in action required because of this.

Please provide update.

**Comment by gchan-trailcon** [comment]
Giovani,
I also asked Ed to check if user is using non-US keyboard layout.

**Comment by giovanicani** [comment]
good point Gary... I didn't think about this possibility.

**Comment by tufailzafar** [comment]
![i127 cimgpsh_orig](https://cloud.githubusercontent.com/assets/5826517/10885187/ff9adeb6-8149-11e5-8cc4-bc0167370a77.png)

in the next release RO status will be checked against server, RO already approved cannot be sent again

**Comment by giovanicani** [comment]
Ed came back saying that the guy was using a windows keyboard instead of the motion tablet keyboard.

Tufail, can you provide an update. If anything will be done on the app side ? If nothing then we can close this ticket. I haven't heard any other problem associated to the keyboard issue. Thanks

**Comment by d3sqa** [comment]
Unicode is now prevented at the time of call to EMDECS. The fix will be available in the next release

**Comment by giovanicani** [comment]
When is this being released ? Tomorrow along with the other changes on the mobile ?

**Comment by giovanicani** [comment]
Another 2 ERRORS due to UNIQUE KEY.

![screen shot 2015-11-11 at 2 14 52 pm](https://cloud.githubusercontent.com/assets/5666297/11100342/ac20791c-887e-11e5-9b83-2595967487b7.png)

**Comment by d3ssupport** [comment]
Hi Giovani,

 

This fix will be released today i.e. on 12th November, 2015 06:00 AM EST. The new release will also include the PMCVI future date issue.

 

Thanks

**Comment by d3sqa** [comment]
Updates are now available at the production. Please update the current version of MRO application. The issue in consideration and the PMCVI future date validation are available in the latest MRO update.

**Comment by giovanicani** [comment]
Thanks TEAM!
