### ISSUE TITLE
Improvements on the MRO Cloud Filter

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#151]
Sort the mechanic list by name (show only active users) and add filter by location and customer. For now search by location and customer will have to be string based (like '%string%'). Cannot be case sensitive.

Let me know once this is done. thanks!
<img width="412" alt="screen shot 2015-11-17 at 4 59 22 pm" src="https://cloud.githubusercontent.com/assets/5666297/11226352/5b6849d6-8d4d-11e5-9698-d9bd9dcb0a59.png">

**Comment by giovanicani** [comment]
Please provide update.

**Comment by giovanicani** [comment]
Why the calendar selection is gone on the MRO ?

![screen shot 2015-11-23 at 3 22 56 pm](https://cloud.githubusercontent.com/assets/5666297/11348722/37a7bf6a-91f6-11e5-9a09-5adcdfd292ed.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The sorting at the 'Mechanic' drop down is done. The calendar issue is also resolved. Both the fixes are available at Prod.
Work in progress on adding Customer and Location to the filter

**Comment by d3sqa** [comment]
Still working on addition of Location and Customer. We will update this ticket once we are completely done with it

**Comment by d3sqa** [comment]
1. The Location and Customer fields has been added in the filter and they are not case sensitive.
2. Alphabetic sort has been applied on the Mechanic drop down.
3. Calendar is also successfully prompted upon clicking on the Date fields.

All the above mentioned fixes are ready for testing at UAT Environment

**Comment by giovanicani** [comment]
done.
